# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c5242a4f1d0a7ac0596d2a3483a450d989d59a8552c5553e46f3d0894a2c0dd7cbe55d5dcdec976d0071548151f63edbbea0c278487370c6475708c1bbf3ffd

test:
  secret_key_base: 4c33b7a2fd48ec23bc57ed1c97125e5628618d6af909fe708bdce539731a2686319053e17ace01e77c1b964d71e5505278990da2ddfae382dc0620b6e0e5d885

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
